version: "3"

services:

  runtime-setup:
    image: swift-cassandra-client:20.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"

  build:
    image: swift-cassandra-client:20.04-main

  test:
    image: swift-cassandra-client:20.04-main
    environment: []
      #- SANITIZER_ARG: "--sanitize=thread"
      #- TSAN_OPTIONS: "no_huge_pages_for_shadow=0 suppressions=/code/tsan_suppressions.txt"

  shell:
    image: swift-cassandra-client:20.04-main
