version: "3"

services:

  runtime-setup:
    image: swift-cassandra-client:22.04-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-jammy"

  build:
    image: swift-cassandra-client:22.04-5.9

  test:
    image: swift-cassandra-client:22.04-5.9
    environment: []
      #- SANITIZER_ARG: "--sanitize=thread"
      #- TSAN_OPTIONS: "no_huge_pages_for_shadow=0 suppressions=/code/tsan_suppressions.txt"

  shell:
    image: swift-cassandra-client:22.04-5.9
