name: Main

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  unit-tests:
    name: Unit tests
    uses: ./.github/workflows/unit_tests.yml
    with:
      linux_5_9_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -strict-concurrency=complete"
      linux_5_10_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -strict-concurrency=complete"
      linux_6_0_arguments_override: "--explicit-target-dependency-import-check error"
      linux_6_1_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error"

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main

  macos-tests:
    name: macOS tests
    uses: apple/swift-nio/.github/workflows/macos_tests.yml@main
    with:
      build_scheme: swift-cassandra-client
      swift_test_enabled: false  # requires running Cassandra server
      watchos_xcode_build_enabled: false  # posix API availability
      tvos_xcode_build_enabled: false  # posix API availability
