name: Main

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    # Workaround https://github.com/nektos/act/issues/1875
    uses: apple/swift-nio/.github/workflows/swift_matrix.yml@main
    with:
      name: "Unit tests"
      matrix_linux_command: "printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d && echo \"deb [signed-by=/etc/apt/keyrings/apache-cassandra.asc] https://debian.cassandra.apache.org 41x main\" | tee -a /etc/apt/sources.list.d/cassandra.sources.list && curl -o /etc/apt/keyrings/apache-cassandra.asc https://downloads.apache.org/cassandra/KEYS && apt-get update && apt install -y default-jre && apt-get install -y cassandra && swift build --explicit-target-dependency-import-check error && while ! nodetool status 2>/dev/null; do echo Waiting for Cassandra.. && sleep 3; done && export CASSANDRA_USER=cassandra && export CASSANDRA_PASSWORD=cassandra && export CASSANDRA_KEYSPACE=cassandra && swift test --explicit-target-dependency-import-check error"

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main
